src/packet/decode.ts, src/transport/index.ts, src/transport/types.ts, src/transport/udp.ts, test/transport/udp.test.ts
Depends on #36 
Add a UDP transport that receives/decodes UDP packets into (sender, `PacketType`, `Packet`)
and encodes/sends (recipient, `PacketType`, `Packet`) via UDP.
=> Add udp transport

src/enr/enr.ts, src/enr/types.ts, src/enr/v4.ts, test/enr.test.ts
`ENR` is now a class the extends `Map`.
This allows us to maintain a sequence number that gets incremented on every `set`.
It also simplifies/standardizes accessing the `record.id`, `record.publicKey`, and `record.seq`.
The aliases `PublicKey`, `PrivateKey`, and `Signature` are also removed in favor of using `Buffer` directly.
=> Refactor ENR as a class

src/enr/constants.ts, src/enr/enr.ts, src/enr/types.ts
Add signature to enr - caches signature in enr, wipes if it is modified. This allows us to encode a previously-decoded enr without the private key.
Add nodeId getter
=> Add signature to enr

src/libp2p/discv5.ts
- findPeers was never being executed
- findPeers would never run because of a reversed predicate
=> Fix startup bugs in libp2p compat

src/enr/enr.ts, test/enr/enr.test.ts
resolves #56 
+ should throw Error `"Invalid record id"`
resolves #59 
+ should throw Error `"Failed to verify enr: No public key"`
=> Add validations to ENR.verify()

package.json
0.2.3 publishing failed (practically speaking) pushing an old build to npm.
Add a prepublishOnly script to avoid in the future.
Will be followed up immediately with a 0.2.4 PR/release.
=> Add build on prepublishOnly

src/libp2p/discv5.ts
libp2p expects the "peer" event to look like this:
```
interface PeerEvent {
id: PeerId;
multiaddrs?: Multiaddr[];
protocols?: string[];
}
```
We were instead returning:
```
interface BadPeerEvent {
id: Promise<PeerId>;
multiaddrs: Multiaddr[]; // but with an undefined multiaddr X_X
}
```
Fix `id` to await the `PeerId`
And skip emitting an event if the given multiaddr, eg: `enr.multiaddrTCP` is undefined.
cc @3xtr4t3rr3str14l who found the bug
=> Fix libp2p peer event

src/service/service.ts, src/session/service.ts
I'd like to print out our node id at startup time so that it's easier to debug with other nodes/peers
=> Print out node id at startup

src/kademlia/kademlia.ts, src/service/service.ts
Fix two bugs:
1. we weren't sending nodes of the right distance, off by one
2. we weren't sending as many nodes in the bucket as we could, only potentially the last node in the bucket
=> Fix kad lookup bugs in NODES response

src/config/index.ts, src/kademlia/lookup.ts, src/kademlia/types.ts
Add a `lookupTimeout` configuration option.
Sets the maximum amount of time to spend on each lookup. Default to 60 seconds.
=> Add lookupTimeout configuration

src/enr/enr.ts, src/libp2p/discv5.ts, src/service/service.ts, src/session/service.ts, src/session/session.ts, test/enr.test.ts, test/session/service.test.ts
Breaking changes:
Instead of using getter/setters `enr.multiaddrUDP` and `enr.multiaddrTCP`,
Use `getLocationMultiaddr(protocol: string): Multiaddr | undefined` and `setLocationMultiaddr(multiaddr: Multiaddr): void`.
This allows us to deduplicate all multiaddr logic into a single getter/setter as well as support multiaddr selection by specific ip4/6 subprotocols like `"udp4"` or `"tcp6"`.
Also add `getFullMultiaddr(protocol)` which returns the multiaddr with `/p2p/${peerId}` appended
=> Refactor ENR multiaddr handling

src/enr/enr.ts, types/multiaddr/index.d.ts
resolves #98 
Refer to https://github.com/multiformats/js-multiaddr/blob/v8.0.0/src/convert.js#L55
=> New multiaddr 0.8.0: use toBytes() instead of toBuffer()

.gitignore, src/enr/enr.ts, src/util/toBuffer.ts, test/enr.test.ts, test/enr/enr.test.ts
js-multiaddr 8.0.0 only expects a Buffer with 0 byte offset, this caused discv5 to use incorrect udp port after decoding from enr and cannot do handshake with other nodes. The issue is (for later reference):
+ Discv5 gets inccorrect udp port after decoding an enr from txt
+ It sends random packets to nodes
+ Receive no packet from then
We expect it to be fixed in https://github.com/multiformats/js-multiaddr/pull/146/files
=> Fix multiaddr port after decoding enr from a txt

src/enr/enr.ts
throws a specific error if we can't find the id in `get` id before calling `toString`
=> check for undefined id in get id

src/message/decode.ts
when distance is `256`, the rlp encode result will be `<Buffer 01 00>`. so we need to use `readUIntBE` instead of `readUInt8`.
=> fix: decodeFindNode

src/service/addrVotes.ts
If `tiebreakerStr` does not exist in `this.tallies`, `best[1]` will be `undefined`, and that will cause comparing failed.
```js
console.log(1 > undefined);
// false
```
=> fix: AddrVotes.best

package.json, src/message/create.ts, src/service/service.ts, src/service/types.ts
Simple TALKREQ/TALKRESP message handling
- discv5.service emits event when a TALKREQ/TALKRESP message is received 
- `discv5.sendTalkReq` broadcasts a a provided `payload` to all nodes in routing table with a given `protocol` in the `TALKREQ` message format
- `discv5.sendTalkResp` sends a TALKRESP message to a specified `nodeId` with a provided `payload`
=> Add handlers/helpers for TALKREQ/TALKRESP message types

bench/enr/index.bench.ts, package.json, src/enr/enr.ts, test/enr.test.ts, yarn.lock
Relies on #124 (for benchmark infra)
Seen in profiles
Added benchmarks to show improvement:
Before:
```
ENR
✓ ENR - getLocationMultiaddr - udp                                    705716.3 ops/s    1.417000 us/op        -      57023 runs  0.104 s
✓ ENR - getLocationMultiaddr - tcp                                    92378.75 ops/s    10.82500 us/op        -      50000 runs  0.565 s
```
After:
```
ENR                                                                                                                                                                                          
✓ ENR - getLocationMultiaddr - udp                                     1739130 ops/s    575.0000 ns/op        -     112916 runs  0.106 s
✓ ENR - getLocationMultiaddr - tcp …
```
=> Optimize enr  getLocationMultiaddr

src/libp2p/discv5.ts, src/service/service.ts, src/service/types.ts, src/session/service.ts
Adds an _optional_ metrics to be passed in, w/ several defined metrics:
- total size of kademlia table
- count of active sessions
- count of active peers
- count of sent messages by message type
- count of received messages by message type
We can add more metrics as we think of them
=> Add metrics

src/session/service.ts
The `src` in the WHOAREYOU error messages is adjusted be the `toString()` value of the source `multiaddr`.  Otherwise the error messages look like
```js
Received a WHOAREYOU packet that references an unknown or expired request. source: Multiaddr, token: e022fd0369fa83381b0bcf74
```
Fixed version now looks like:
```js
Received a WHOAREYOU packet that references an unknown or expired request. source: /ip4/0.0.0.0/tcp/5500/wss, token: 6c22f64bf71b9d81ff3bfef9
```
=> fix src value in WHOAREYOU error messages

package.json, src/keypair/index.ts, yarn.lock
Ensure the tree contains no uint8arrays version under 3.0.0
CC https://github.com/libp2p/js-libp2p/issues/967 @wemeetagain
=> Bump libp2p deps for uint8arrays@3.0.0

src/service/service.ts, src/service/types.ts
While integrating the metrics into lodestar ( chainsafe/lodestar#3103 ) it seemed like this useful metric was missing
We want to track how often lookups are triggered, especially when they are triggered by lodestar on demand ( chainsafe/lodestar#3104 )
=> Add lookup count metric

src/service/addrVotes.ts
**Motivation**
As noted in https://github.com/ChainSafe/lodestar/issues/3390#issuecomment-956042391, the timeout map of `votes` in `AddrVotes` uses the wrong callback function, and it causes the `tallies` map contains > 34000 entries with node id as key `NaN` as value
**Description**
Fix the creation of `votes` timed out map
=> AddrVotes: Fix timeout map

src/config/index.ts, src/kademlia/types.ts, src/kademlia/util.ts, src/service/service.ts
Discv5.1 allows FINDNODE to request nodes at multiple distances.
We can use this to get more diverse nodes per request.
Inspiration here: https://github.com/status-im/nim-eth/blob/master/eth/p2p/discoveryv5/protocol.nim#L101
=> Query multiple distances at once in lookups

src/service/service.ts
The `broadcastTalkReq` message implemented by #122 doesn't return anything at present so the parent application isn't currently able to match up messages sent with `TALKRESP` messages received from the network.
This PR converts `broadcastTalkReq` to a promise based method that returns the first response it receives from the network or else rejects after a 1 second timeout.
=> Convert `broadcastTalkReq` to return promise

src/config/index.ts, src/service/addrVotes.ts, src/service/service.ts, test/service/addrVotes.test.ts
**Motivation**
+ Start from @dapplion bound AddrVotes data structures which make it simple to find a winning vote
+ When there is enough vote configured by `addrVotesToUpdateEnr` (10 by default), the `addVote()` api returns the winning vote
+ If there are more than `MAX_VOTES` (200), remove the oldest
**Description**
Since this is a new implementation of address vote, this should close #150
=> Bound AddrVotes data structures

src/enr/enr.ts, src/message/decode.ts, test/unit/enr/enr.test.ts, test/unit/message/codec.test.ts
There is now a problem with encoding and decoding enr addresses because `toNewUint8Array` should be called before `muConvert.toString`
=> fix: add toNewUint8Array when decoding enr values

package.json
Bumping this dependency upgrades several transitive dependencies down the dependency tree (notable `libp2p/crypto` which in turn switches from the deprecated `noble-secp256k1` to the updated/namespaced `@noble/secp256k1`).  The only potentially impactful breaking change here is `peer-id` v0.16.0 requires Node v15+.  We've been using this version of `peer-id` in the `portalnetwork` module for a while now with no ill effects and I'd like to remove the deprecated `noble-secp256k1` module from our dependency tree.
=> chore: Bump peer-id dep to latest

src/session/nodeInfo.ts
The `service.sendTalkRequest` takes a `multiaddr` as an optional input (either that or ENR).  When a `multiaddr` is passed in, the `createNodeContact` method which is used internally to construct the `NodeContact` object used to retrieve the session requires that any multiAddr inputs specify the nodeId in the `/p2p/` protocol of the multiaddr.  However, the session key used to to reference individual sessions is a combination of the `nodeId` and the hex encoded bytes of just the location multiaddr for the UDP socket associated with the session.  This PR filters the p2p protocol out of the multiaddr input when constructing the session key used to retrieve a session so that this `sendTalkRequest` method now works properly.
=> fix: Remove p2p portions of multiaddr in `nodeAddressToString`

package.json
Adds `packet` to the `exports` field in package.json as we're using this in Ultralight and don't seem to be able to import it properly without hacking the package.json in node_modules after install
=> feat: add `packet` to package.json `exports

.github/workflows/pr.yaml
Discv5 repo uses https://github.blog/changelog/2022-05-11-default-to-pr-titles-for-squash-merge-commit-messages/
=> chore: disable validateSingleCommit

package.json, src/message/encode.ts, src/service/addrVotes.ts, yarn.lock
**Motivation**
- Majority of modules in lodestar goes with the last performant version of `is-ip` which is 4.0.0
- `v4.0.0` is a breaking change, this gives lodestar a chance to enforce `is-ip@4.0.0` to avoid the performance issue in v5.0.0
**Description**
Migrate `is-ip` to v4.0.0
=> chore: migrate to is-ip 4.0.0

src/service/service.ts
This PR fixes a few things in the FINDNODE request handler:
* We should filter out invalid/duplicate distances.
* According to [the spec](https://github.com/ethereum/devp2p/blob/master/discv5/discv5-wire.md#findnode-request-0x03), the recommended result limit is 16, not 15.
* When returning an empty response, `total` should be one.
=> fix: add more checks to handleFindNode

src/message/decode.ts, src/message/encode.ts, test/unit/message/codec.test.ts
According to [the spec](https://github.com/ethereum/devp2p/blob/master/discv5/discv5-wire.md#pong-response-0x02), `recipient-port` is an (unsigned) 16-bit integer. This PR ensures that those port values are valid.
* Remove a commented out line of code, doesn't seem useful to keep.
* When decoding, check that the length of the field isn't greater than 2 bytes.
* When encoding, check that the number is in the valid port range.
* Add a test for encoding a PONG message with a 1-byte port.
* Add a new test function that handles invalid messages.
=> fix: throw error when encoding/decoding PONG with invalid port

src/session/constants.ts, src/session/service.ts
According to [the spec](https://github.com/ethereum/devp2p/blob/master/discv5/discv5-wire.md#nodes-response-0x04):
> Implementations may place a limit on the allowed maximum for total. If exceeded, additional responses may be ignored.
This PR implements this feature. It will ignore response packets after `MAX_NODES_TOTAL_PACKETS` (16). This should be more than enough, considering the FINDNODE request handler should limit the result to 16 nodes, which can be fit into 6 packets if packed correctly.
=> feat: limit nodes response to 16 packets

src/session/constants.ts, src/session/service.ts
My PR from yesterday was a mistake. I thought it was handling the nodes response, but it was handling the nodes response *request*. So the original version works just fine. My bad, sorry about that.
And that feature I added already existed, here:
https://github.com/ChainSafe/discv5/blob/f2cc802fd7fb65c5fddfa4d375f9ac58b2af13f9/src/service/service.ts#L849-L856
Associated with #219.
=> fix: revert limit to nodes response

src/service/service.ts, src/service/types.ts
Expose FINDNODE and PING for downstream consumers
`sendFindNode(remote: ENR | Multiaddr, distances: number[]): Promise<ENR[]>`
`sendPing(remote: ENR | Multiaddr): Promise<PongResponse>`
=> feat: expose find node and ping

src/service/service.ts
**Motivation**
- When handling FindNodes request, if distance is 0 we always call `this.enr.encodeToValues(privateKey)` which sign the enr content, this is to make sure we have a signature in our enr
- I debug a node running several days, the `seq` in enr is only 11n, it means that there are not a lot of modification that cause us to sign the enr
**Description**
- Check signature before calling `this.enr.encodeToValues`
- Add more comments
this could be related to #201
=> fix: ensure our enr has signature in INodesMessage response

src/enr/enr.ts, test/unit/enr.test.ts
The cached signature should be deleted when enr keys are deleted.
Otherwise, when the enr is serialized, it will write an invalid signature instead of requiring a new signature to be crafted.
=> fix: delete signature on enr.delete

src/libp2p/discv5.ts, src/service/service.ts, src/session/nodeInfo.ts, src/session/service.ts, src/transport/types.ts, src/transport/udp.ts, src/util/ip.ts, test/e2e/connect.test.ts, test/e2e/mainnetBootnodes.test.ts, test/unit/service/service.test.ts, test/unit/session/service.test.ts, test/unit/transport/udp.test.ts, test/unit/util/ip.test.ts
Resolves #167
- Adds the capability to specify either an ip4, ip6, or both bind addresses instead of just a single bind address
- By specifying the addresses to bind to, this sets the `IPMode` (either ip4, ip6, or both).
- Based on the specified `IPMode`, several things happen:
- a udp4 socket and/or a udp6 socket are opened
- discovered peers will be contacted based on the proper entry in their enr (either ip+udp or ip6+udp6) (ip6 is the default in the case of the 'both' IPMode) using the proper socket
=> feat!: add IPv6 support

package.json
Adds `lru-cache` to dependencies so it can be found in library consumer dependency trees.
=> fix: Add lru-cache to deps

package.json, src/service/service.ts, src/transport/udp.ts, yarn.lock
Removes `dgram` as a dependency as this is a core Nodejs module now.  Will also keep this npm warning message from appearing when installing dependencies for discv5.
`npm WARN deprecated dgram@1.0.1: npm is holding this package for security reasons. As it's a core Node module, we will not transfer it over to other users. You may safely remove the package from your dependencies.`
=> chore: remove dgram from package.json

bench/enr/index.bench.ts, bench/keypair/index.bench.ts, src/enr/enr.ts, src/enr/index.ts, src/enr/peerId.ts, src/enr/util.ts, src/enr/v4.ts, src/keypair/index.ts, src/keypair/secp256k1.ts, src/keypair/types.ts, src/service/service.ts, src/session/crypto.ts, src/session/nodeInfo.ts, src/session/session.ts, src/transport/types.ts, src/transport/udp.ts, src/util/toBuffer.ts, test/unit/enr/enr.test.ts, test/unit/kademlia/kademlia.test.ts, test/unit/keypair/index.test.ts, test/unit/service/service.test.ts, test/unit/session/crypto.test.ts, test/unit/session/service.test.ts, test/unit/util/ip.test.ts
This is a prerequisite towards pulling the enr code into a separate package.
The core change here is de-tangling the enr code from the rest of the discv5 code.
One consideration there is allowing the cryptography to be swapped out by consumers. Generally, the fastest crypto implementations aren't browser compatible, or are overkill when installing a package (requiring lengthy compilation step when npm intsalling).
A future PR will remove bcrypto as the default crypto impl.
BREAKING CHANGE:
- remove `enr.keypair`
- export enr v4 crypto from `getV4Crypto` function
- replace `createKeypairFromPeerId` and vice versa with `createPublicKeyFromPeerId`
- refactor `createKeypair`
=> feat!: add pluggable enr crypto interface

packages/enr/src/v4.ts
- #266 created an abstract interface that operates on Uint8Arrays, however bcrypto is strict and requires Buffers as inputs
- Explicitly coerce all bcrypto inputs to be Buffers
=> fix: coerce Buffers in bcrypto crypto

packages/discv5/src/service/service.ts
BREAKING CHANGE:
`broadcastTalkReq` has been removed since it was very opinionated and can be trivially reproduced using `kadValues` and `sendTalkReq`.
```ts
function broadcastTalkReq(
discv5: IDiscv5, payload: Buffer, protocol: string | Uint8Array
): Promise<Buffer> {
const requests = []
for (const enr of discv5.kadValues()) {
requests.push(discv5.sendTalkReq(enr, payload, protocol)
}
// Depending on the use case
// you might want to replace with Promise.allSettled
// to return all responses / errors
return Promise.race(requests)
}
```
=> feat!: remove broadcastTalkReq

.eslintrc.cjs, packages/discv5/src/service/service.ts, packages/discv5/src/service/types.ts, packages/discv5/src/session/crypto.ts, packages/discv5/src/session/nodeInfo.ts, packages/discv5/src/session/service.ts, packages/discv5/src/session/session.ts, packages/discv5/src/session/types.ts, packages/discv5/test/e2e/connect.test.ts, packages/discv5/test/unit/session/crypto.test.ts, packages/discv5/test/unit/session/service.test.ts
- https://github.com/ChainSafe/discv5/issues/265
- https://github.com/ChainSafe/lodestar/issues/6320
- refactor callback handling
- move from callback style `(err, resp) => void` to deferred promise style `{resolve: (err) => void, reject: (err) => void}`
- ensure callbacks are called in each rpc handler and in each error case
- remove hanging promises
- add linter rule to ensure nothing remaining
- move error handling of node contacts into `getNodeContact` rather than the `getNodeAddress` "getter"
- this makes error handling much more predictable, throwing upfront, rather than waiting for a later event to trigger an error
- wrap rpc handlers in try/catch statements
- ensure that logic handed in rpc request and response handlers are unable to trigger unhandled exceptions
=> fix: improve error handling

packages/enr/package.json, packages/enr/src/create.ts, packages/enr/src/defaultCrypto.ts, packages/enr/src/enr.ts, packages/enr/src/index.ts, packages/enr/src/util.ts, packages/enr/test/unit/enr.test.ts
In order to make `@chainsafe/enr` more usable as a library, avoid usage of `Buffer` unless it exists as `globalThis.Buffer`.
=> feat: constrain usage of Buffer in enr package

packages/enr/src/enr.ts, packages/enr/test/unit/enr.test.ts
- Add support to get/set `quic` and `quic6` enr entries
- Add support to get/set quic-v1 multiaddrs from an enr
- extract multiaddr parsing into a separate function
- See https://github.com/ethereum/consensus-specs/pull/3644
=> feat(enr): add quic support

.github/workflows/test_and_release.yml
- As brought up in https://github.com/ChainSafe/discv5/pull/302 we're currently using an older version of nodejs in ci
- Use the current LTS version, 22
=> chore: use node 22 in ci

packages/enr/src/util.ts
This is a fix for a bug in the `ENR` package that was causing discv5 errors in ultralight. 
`enr/src/util.ts` exports a helper function `bytesToBigInt(bytes: Uint8Array): bigint`
This function uses `bytesToHex` from `ethereum-cryptography/utils` to convert the `Uint8Array` to a hex string, and then `BigInt()` to convert the hex string to `bigint`.
The bug occurs when the length of `bytes` is 0.  `bytesToHex` returns an empty string, and trying to call `BigInt('0x')` throws an error.
Fix: simply return `0n` if `bytes.length === 0`
=> fix:  BigInt conversion bug

packages/discv5/src/message/create.ts, packages/discv5/src/message/decode.ts, packages/discv5/src/message/encode.ts, packages/discv5/src/message/types.ts, packages/discv5/src/service/service.ts, packages/discv5/src/session/service.ts, packages/discv5/src/session/types.ts, packages/discv5/test/unit/message/codec.test.ts
Fix for issue #309 
This is a fix for a number of hive tests.  Here is an [example](https://portal-hive-experimental.ethdevops.io/suite.html?suiteid=1744230445-096c31f89428ef5aa5e2c28dc5b7cffe.json&suitename=discv5#test-6)
The tests fail with errors like this:
` wrong request ID 01 in TALKRESP, want 00000001`
----
This is happening because when we `decode` an incoming `TalkRequest`, we store the `request.id` in memory as a `bigint`, using a `bytesToBigint` conversion.  
Then when we `encode` the `TalkResponse`, we convert the `request.id` back from a `bigint` to bytes using `bigintToBytes`.  
The requesting node compares the `response.id` to the `request.id` that it sent, and since the bytes are not equal, it throws a `wrong request ID` error.
In the example above:
`request.id = …
=> fix: leading zeros stripped from request id

packages/discv5/src/session/service.ts
Fix for failing hive test [PingHandshakeInterrupted](https://portal-hive-experimental.ethdevops.io/suite.html?suiteid=1744230445-096c31f89428ef5aa5e2c28dc5b7cffe.json&suitename=discv5#test-5) 
**Test `PingHandshakeInterrupted` starts a handshake, but doesn't finish it and sends a second ordinary message
packet instead of a handshake message packet. The remote node should respond with
another WHOAREYOU challenge for the second packet.**
----
`@chainsafe/discv5` fails to do this.  The `sendChallenge` method is called,  but first checks to see if we already sent a challenge, and if so, simply returns without sending a new challenge.
This PR removes the condition from `sessionService.sendChallenge` which prevents a new challenge from being sent.  The new challenge simply replaces the old one …
=> fix: SessionService should send challenge even with active challenge

packages/discv5/src/transport/udp.ts, packages/discv5/test/unit/transport/udp.test.ts
- Remove the faulty error condition "bind multiaddrs must have different ports"
- Allow ip4 and ip6 to use the same port
=> fix: allow dual stack to use the same port
